# Generated by Django 3.0.7 on 2020-07-06 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='income',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='merchantName',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='reputation',
        ),
    ]
