# Generated by Django 3.0.7 on 2020-07-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_auto_20200706_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='income',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='merchant',
            name='merchantName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='merchant',
            name='reputation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='phone',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
