# Generated by Django 3.0.7 on 2020-07-06 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchant', '0003_auto_20200706_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusID', models.IntegerField()),
                ('addr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusID', models.IntegerField()),
                ('goodID', models.CharField(max_length=32)),
                ('goodNum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CommentonGood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodID', models.IntegerField()),
                ('cusID', models.IntegerField()),
                ('content', models.TextField()),
                ('rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cusID', models.IntegerField()),
                ('orderID', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('merchID', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=32)),
                ('num', models.IntegerField()),
                ('description', models.TextField(max_length=255, verbose_name='商品描述')),
                ('goodSta', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MerchCus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusID', models.IntegerField()),
                ('mercID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MerchGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchID', models.IntegerField()),
                ('goodID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MerchOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchID', models.IntegerField()),
                ('orderID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('starttime', models.DateTimeField(auto_now_add=True)),
                ('modtime', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=100)),
                ('transSta', models.IntegerField()),
                ('afterSta', models.IntegerField()),
                ('modSta', models.IntegerField()),
                ('goodNum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrdersCus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusID', models.IntegerField()),
                ('mercID', models.IntegerField()),
                ('ordID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niname', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
