# Generated by Django 3.0.7 on 2020-07-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_addresses_admin_cart_commentongood_complaints_customer_good_merchcus_merchgoods_merchorders_order_or'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('merchID', models.IntegerField()),
                ('goodsName', models.CharField(max_length=32)),
                ('image', models.CharField(max_length=128)),
                ('price', models.FloatField(default=0)),
                ('type', models.CharField(max_length=32)),
                ('num', models.IntegerField()),
                ('description', models.TextField(max_length=255, verbose_name='商品描述')),
                ('goodSta', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Good',
        ),
    ]
