# Generated by Django 3.0.7 on 2020-07-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0006_auto_20200707_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goodSta',
            field=models.IntegerField(blank=True),
        ),
    ]
