# Generated by Django 3.0.7 on 2020-07-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0008_remove_goods_goodsta'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goodSta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goodsName',
            field=models.CharField(max_length=32),
        ),
    ]
