# Generated by Django 3.0.7 on 2020-07-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0009_auto_20200707_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cusID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='goodID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='merchID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='order',
            name='afterSta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='goodNum',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='modSta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='transSta',
            field=models.IntegerField(default=0),
        ),
    ]
