# Generated by Django 3.0.7 on 2020-07-07 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0010_auto_20200707_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='goodID',
            new_name='goodsID',
        ),
    ]
