# Generated by Django 3.0.7 on 2020-07-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0011_auto_20200707_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='goodID',
            new_name='goodsID',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='goodNum',
            new_name='goodsNum',
        ),
        migrations.RenameField(
            model_name='commentongood',
            old_name='goodID',
            new_name='goodsID',
        ),
        migrations.RenameField(
            model_name='merchgoods',
            old_name='goodID',
            new_name='goodsID',
        ),
    ]
