# Generated by Django 3.0.7 on 2020-07-07 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0012_auto_20200707_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='goodSta',
            new_name='goodsSta',
        ),
    ]
