# Generated by Django 3.0.7 on 2020-07-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0013_auto_20200707_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default=0, max_length=128),
        ),
    ]
