# Generated by Django 3.0.7 on 2020-07-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0014_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='goodsID',
            field=models.IntegerField(),
        ),
    ]
