# Generated by Django 3.0.7 on 2020-07-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0015_auto_20200709_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='goodNum',
            new_name='goodsNum',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment',
            new_name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='paySta',
            field=models.IntegerField(default=0),
        ),
    ]
