# Generated by Django 3.0.7 on 2020-07-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0016_auto_20200709_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
