# Generated by Django 3.0.7 on 2020-07-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0017_complaints_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='frozen',
            field=models.IntegerField(default=0),
        ),
    ]
